
insert into field(values (1, 'Genie'));
insert into field(values (2, 'Arts, lettres et langues'));
insert into field(values (3, 'Droit'));
insert into field(values (4, 'Environnement et développement durable'));
insert into field(values (5, 'Études plurisectorielles'));
insert into field(values (6,'Administration résultats'));
insert into field(values (7, 'Informatique'));
insert into field(values (8, 'Musique'));
insert into field(values (9, 'Sciences de l activité physique'));
insert into field(values (10, 'Sciences de la sante'));
insert into field(values (11, 'Sciences de leducation Sciences humaines'));
insert into field(values (12, 'Sciences pures'));


insert into program(values (1, 'Genie Informatique',1));
insert into program(values (2, 'Genie Electrique',1));
insert into program(values (3, 'Genie Robotique',1));
insert into program(values (4, 'Genie Civil',1));



insert into ap(values('GIF601','Conception d une application integrant des objets connectes'));
insert into ap(values('GIF690','Physique des ondes'));
insert into ap(values('GEI240','Circuits de communication'));
insert into ap(values('GEI335','Physique des composants electroniques'));
insert into ap(values('GEI340','Conception de circuits integres VLSI'));
insert into ap(values('GEI346','Fabrication de circuits integres'));
insert into ap(values('GEI355','Fabrication de circuits electroniques'));
insert into ap(values('GEI410','Microprocesseurs'));
insert into ap(values('GEI415','Applications de microprocesseurs'));
insert into ap(values('GEI430','Architecture et organisation des ordinateurs'));
insert into ap(values('GEI431','Architecture des ordinateurs II'));
insert into ap(values('GEI435','Conception de systemes e  micro'));
insert into ap(values('GEI437','Laboratoire dinterfaces et microprocesseurs'));
insert into ap(values('GEI441','Conception de logiciels'));
insert into ap(values('GEI442','Structures de donnees et algorithmes'));
insert into ap(values('GEI443','Organisation des langages et compilation'));
insert into ap(values('GEI446','Programmation des systemes'));
insert into ap(values('GIF640','Systemes dexploitation'));
insert into ap(values('GEI448','Systemes dexploitation'));
insert into ap(values('GEI450','Projet de conception de logiciels'));
insert into ap(values('GEI452','Base de donnees'));
insert into ap(values('GEI455','Systemes en temps reel'));
insert into ap(values('GEI457','Intelligence artificielle et langages associes'));
insert into ap(values('GEI460','Reseaux et teleinformatique'));
insert into ap(values('GEI465','Systemes repartis'));
insert into ap(values('GEI500','Communications'));
insert into ap(values('GEI540','Systemes de communication'));
insert into ap(values('GEI600','Systemes et signaux'));
insert into ap(values('GEI605','Traitement du signal'));
insert into ap(values('GEI610','Asservissements'));
insert into ap(values('GEI615','Simulation et conception de systemes'));
insert into ap(values('GEI640','Commande numerique'));
insert into ap(values('GEI717','Biophotonique'));
insert into ap(values('GEI722','Microcapteurs biophotoniques sur puce'));
insert into ap(values('GEI739','Ingenierie de lintelligence'));
insert into ap(values('GEI748','Modulation avancee'));
insert into ap(values('GEI749','electronique hautes frequences'));
insert into ap(values('GEI765','Architecture de reseaux'));
insert into ap(values('GEI766','Composantes de reseaux'));
insert into ap(values('GEI767','Gestion de reseaux'));
insert into ap(values('GEN410','GEN410'));
insert into ap(values('GEN440','GEN440'));
insert into ap(values('GEN450','GEN450'));
insert into ap(values('GIF400','Conception dun systeme dynamique'));
insert into ap(values('GLO800','GLO800'));
insert into ap(values('GIF670','Objets connectes'));
insert into ap(values('GSI830','Protection active des systemes informatiques'));
insert into ap(values('GIF671','Objets connectes'));
insert into ap(values('GEL350','elements de statistiques'));
insert into ap(values('GEL361','Phenomenes dechange de chaleur'));
insert into ap(values('GEL801','Projet majeur en genie electrique II'));
insert into ap(values('GEL320','electronique analogique II'));
insert into ap(values('BGE311','Instrumentation en bio-ingenierie I'));
insert into ap(values('BGE312','Instrumentation en bio-ingenierie II'));
insert into ap(values('BGE313','Instrumentation en bio-ingenierie III'));
insert into ap(values('GAR710','Automatique industrielle'));
insert into ap(values('GAR720','Commande numerique'));
insert into ap(values('GEN123','Algebre lineaire et calcul matriciel'));
insert into ap(values('GEN131','Circuits electriques'));
insert into ap(values('GIA710','Intelligence artificielle formalisable'));
insert into ap(values('GIA720','Intelligence artificielle bio-inspiree'));
insert into ap(values('GEL311','Physique des semi-conducteurs II'));
insert into ap(values('GIF560','Statistiques et fiabilite des systemes'));
insert into ap(values('GIF401','Conception de systeme de traitement numerique'));
insert into ap(values('GIF320','Systemes dexploitation'));
insert into ap(values('GIF331','Reseaux et protocoles de communication'));
insert into ap(values('GEN210','Mathematiques des signaux a  temps continu'));
insert into ap(values('GEL370','Communication graphique'));
insert into ap(values('GIF600','Conception dun systeme informatique distribue'));
insert into ap(values('GEI701','Activites de recherche et memo'));
insert into ap(values('GEI200','Mesures electriques'));
insert into ap(values('GEI768','GEI768'));
insert into ap(values('GEI801','GEI801'));
insert into ap(values('GEL201','GEL201'));
insert into ap(values('GEL211','GEL211'));
insert into ap(values('GEL431','Asservissements analogiques'));
insert into ap(values('GEN240','GEN240'));
insert into ap(values('GIA731','Intelligence artificielle probabiliste'));
insert into ap(values('GIF201','GIF201'));
insert into ap(values('GEI770','Reseaux de communication par fibre optique'));
insert into ap(values('GIF230','GIF230'));
insert into ap(values('GMB720','GMB720'));
insert into ap(values('GRO810','GRO810'));
insert into ap(values('GRO820','GRO820'));
insert into ap(values('GSI810','Methodes de cryptographie'));
insert into ap(values('GSI820','Reseautique securisee'));
insert into ap(values('GIF655','Propagation dondes electromagnetiques'));
insert into ap(values('GEL511','Traitement numerique des signaux'));
insert into ap(values('GEL601','Conception dun systeme de communication'));
insert into ap(values('BGE301','Instrumentation en bio-ingenierie I'));
insert into ap(values('BGE302','Instrumentation en bio-ingenierie II'));
insert into ap(values('GIF630','Securite informatique et cryptographie'));
insert into ap(values('GEN600','Ethique'));
insert into ap(values('GIF460','Mecanique pour realite virtuelle'));
insert into ap(values('GEI100','Electromagnetisme'));
insert into ap(values('GEI120','Electrotechnique'));
insert into ap(values('GEI130','Radiation et antennes'));
insert into ap(values('GEI205','Circuits'));
insert into ap(values('GEI210','Electronique I'));
insert into ap(values('GEN143','Introduction e  la programmation'));
insert into ap(values('GIF443','Traitement numerique des signaux'));
insert into ap(values('GEI105','Hautes frequences'));
insert into ap(values('GEI215','electronique II'));
insert into ap(values('GEL650','electronique II'));
insert into ap(values('GEI301','GEI301'));
insert into ap(values('GEI785','electronique pour traction de forte puissance'));
insert into ap(values('GIF362','Mathematiques discretes IV'));
insert into ap(values('GEI220','Applications de lelectronique'));
insert into ap(values('GEI752','Techniques avancees de traitement des signaux'));
insert into ap(values('GEL610','Communications analogiques et numeriques'));
insert into ap(values('GEN271','Chimie et physique de lenvironnement'));
insert into ap(values('GEL630','Antennes et propagation non guidee'));
insert into ap(values('GIF421','Modelisation et simulation'));
insert into ap(values('GEI155','Reseaux de distribution electrique'));
insert into ap(values('GEL432','Asservissements analogiques'));
insert into ap(values('GEI778','Automatique industrielle'));
insert into ap(values('GEN701','GEN701'));
insert into ap(values('GEN801','GEN801'));
insert into ap(values('GEL641','Introduction aux reseaux et protocoles'));
insert into ap(values('GEI776','Projet dintegration en securite logicielle'));
insert into ap(values('GEL420','Modelisation'));
insert into ap(values('GEN650','Calcul vectoriel'));
insert into ap(values('GIF442','Traitement numerique des signaux'));
insert into ap(values('GIF550','Systemes embarques reseautes'));
insert into ap(values('GEL620','Propagation guidee dondes electromagnetiques'));
insert into ap(values('GEI779','Commande numerique'));
insert into ap(values('GEL520','electronique et interfaces'));
insert into ap(values('GEI774','Concepts de cryptographie et de securite'));
insert into ap(values('GEI712','Neurophysiologie appl. aux protheses sensori.'));
insert into ap(values('GEI715','Concep. VLSI en fonct. des tests et cmos anal.'));
insert into ap(values('GEI730','Conception par les objets'));
insert into ap(values('GEI740','Programmation de robots mobiles'));
insert into ap(values('GEI746','Modelisation de linformation'));
insert into ap(values('GEI747','Quantification'));
insert into ap(values('GEL301','Conception dun instrument de mesure'));
insert into ap(values('GEI763','Conception de protocoles et services'));
insert into ap(values('GEI759','Ingenierie des systemes numeriques'));
insert into ap(values('GEI764','Validation et tests de protocoles et services'));
insert into ap(values('GEI735','Integration materiel-logiciel'));
insert into ap(values('GIF592','Espaces vectoriels'));
insert into ap(values('GEI775','Projet dintegration en securite informatique'));
insert into ap(values('GIF660','Systemes de multiplexage et de commutation'));
insert into ap(values('GEI783','Commande non lineaire'));
insert into ap(values('GEL500','Conception dun systeme embarque'));
insert into ap(values('GLO700','GLO700'));
insert into ap(values('GEL450','Methodes numeriques'));
insert into ap(values('GEL530','Microprocesseurs'));
insert into ap(values('GEN270','La matiere: proprietes chimiques et physiques'));
insert into ap(values('GIF450','Calcul discret'));
insert into ap(values('GIN656','Stage VI en genie informatique'));
insert into ap(values('GEI742','Intelligence pour robots mobiles et autonomes'));
insert into ap(values('GEI751','Quantification vectorielle'));
insert into ap(values('GIF643','Programmation concurrente'));
insert into ap(values('BGE713','Instrumentation en bio-ingenierie III'));
insert into ap(values('GEI815','Verification fonctionnelle des systemes mixtes analogiques-numeriques'));
insert into ap(values('GIN655','Stage V en genie informatique'));
insert into ap(values('GEI166','Machine synchrone et traction electrique'));

insert into ap(values('GIF521','Proprietes des materiaux'));
insert into ap(values('GEI890','Preparation de donnees pour systemes intelligents'));
insert into ap(values('GEL521','Identification et modelisation'));
insert into ap(values('GEL660','Processus aleatoires'));
insert into ap(values('GIF540','Noyaux tps reel et programmation concurrente'));
insert into ap(values('GIF510','Systemes e  microprocesseurs'));
insert into ap(values('GEI805','Projet de developpement en genie electrique II'));
insert into ap(values('GEL212','Electronique analog. et analyse freq.'));
insert into ap(values('GEN160','Physique des ondes'));
insert into ap(values('GEN502','Sante et securite'));
insert into ap(values('GEN133','Lois fondamentales de lelectricite'));
insert into ap(values('GIF530','Circuits dentrees/sorties et dinterfaces'));
insert into ap(values('BGE712','Instrumentation en bio-ingenierie II'));
insert into ap(values('GEN182','Modelisation 2d'));
insert into ap(values('GEN134','Electricite et magnetisme'));
insert into ap(values('GEI845','Introduction a la robotique humanoide'));
insert into ap(values('BGE711','Instrumentation en bio-ingenierie I'));
insert into ap(values('GEN150','Physique des semi-conducteurs I'));
insert into ap(values('GEI773','Introduction de  linvestigation numerique'));
insert into ap(values('GIF370','Ondes et propagation electromagnetiques'));
insert into ap(values('GEN146','Introduction e  la programmation et aux algorithmes'));
insert into ap(values('GEI825','Calcul et informatique quantiques'));
insert into ap(values('GIF801','Projet majeur en genie informatique II'));
insert into ap(values('GEL340','Electrotechnique'));
insert into ap(values('GEN180','Modelisation 2D et 3d'));
insert into ap(values('GIF380','Securite informatique et cryptographie'));
insert into ap(values('GEI710','Conception avancee de circuits integres'));
insert into ap(values('GEL421','Identification et modelisation'));
insert into ap(values('GEI883','Commande numerique'));
insert into ap(values('GEN170','Realisation et mesure de circuits electriques'));
insert into ap(values('GEI736','Logique floue'));
insert into ap(values('GEI754','Traitement de limage'));
insert into ap(values('GEI771','Programmation securisee'));
insert into ap(values('GEI727','Definition du projet de recherche'));
insert into ap(values('GIF580','Physique des ondes'));
insert into ap(values('GEI807','Definition du projet dessai'));
insert into ap(values('GEN137','Electricite et circuits electriques'));
insert into ap(values('GEN111','La communication et le travail en equipe'));
insert into ap(values('GEN101','Resolution de probleme et conception en genie'));
insert into ap(values('GEI810','Conception avancee de circuits integres'));
insert into ap(values('GIF590','Methodes numeriques'));
insert into ap(values('GIF261','Mathematiques discretes III'));
insert into ap(values('GEN441','Mecanique pour ingenieurs'));
insert into ap(values('GEI822','Matiere'));
insert into ap(values('GEN124','Mathematiques de base pour lingenieur'));
insert into ap(values('GEN136','Circuits electriques II'));
insert into ap(values('GEL803','Projet majeur en energie electrique II'));
insert into ap(values('GEI720','Commande multivariable appliquee e  laerospatiale'));
insert into ap(values('GEI877','Circuits supraconducteurs quantiques'));
insert into ap(values('GIF673','Reseaux sans fil'));
insert into ap(values('GIF570','Traitement numerique des signaux'));
insert into ap(values('GEI772','Securite web'));
insert into ap(values('GIF350','Modeles de conception'));
insert into ap(values('GEI797','Developpement lean en genie informatique'));
insert into ap(values('GIF301','Conception dune architecture de systeme'));
insert into ap(values('GIF611','Systemes dexploitation repartis'));
insert into ap(values('GEL401','Conception dun systeme asservi'));
insert into ap(values('GEI798','Developpement de programmes concurrents'));
insert into ap(values('GEN122','Equations differentielles lineaires'));
insert into ap(values('GEI728','Seminaires de recherche'));
insert into ap(values('GEL611','Communications analogiques et numeriques'));
insert into ap(values('GIF332','Reseaux et protocoles de communication'));
insert into ap(values('GEL315','Electromagnetisme'));
insert into ap(values('GEI806','Projet de developpement en genie informatique II'));
insert into ap(values('GEL331','Electronique de puissance'));
insert into ap(values('GEI726','Introduction au projet de recherche'));
insert into ap(values('GIF680','Physique des materiaux et capteurs'));
insert into ap(values('GIF302','Conception dun systeme informatique distribue'));
insert into ap(values('GIF371','Ondes guidees'));
insert into ap(values('GIF685','Chimie de lalimentation electrique'));
insert into ap(values('GIF391','Systemes distribues et informatique en nuage'));
insert into ap(values('GIF642','Systeme dexploitation'));
insert into ap(values('GEI803','Projet de developpement en genie electrique I'));
insert into ap(values('GIF672','Interfaces entrees sorties'));
insert into ap(values('GEI705','Etude specialisee III'));
insert into ap(values('GEN144','Programmation et algorithmes'));
insert into ap(values('GIF675','Objets connectes'));
insert into ap(values('GEL662','Elements de statistique'));
insert into ap(values('GEL342','Elements de circuits en courant alternatif et transformateurs de puissance'));
insert into ap(values('GEL355','Calcul differentiel et integral multivariable et vectoriel'));
insert into ap(values('GEL302','Conception dun systeme electrotechnique'));
insert into ap(values('GEL335','Production'));
insert into ap(values('GIF620','Bases de donnees'));
insert into ap(values('GEN241','Modelisation et programmation orientees objet'));
insert into ap(values('GEL665','Processus aleatoires'));
insert into ap(values('BGE721','Modelisation en conception d instruments medicaux'));
insert into ap(values('GEL345','Machines electriques tournantes'));
insert into ap(values('GEL625','Lignes de transmission'));
insert into ap(values('GIF644','Systemes temps reel'));
insert into ap(values('GEL651','electronique II'));
insert into ap(values('GEN501','Droit'));
insert into ap(values('GEL802','Projet majeur en energie electrique II'));
insert into ap(values('GIF701','Projet majeur en genie informatique I'));
insert into ap(values('GEL661','Statistiques et probabilites'));
insert into ap(values('GEL701','Projet majeur en genie electrique I'));
insert into ap(values('GIF691','Physique des ondes'));
insert into ap(values('GIN666','Stage VI en genie electrique'));
insert into ap(values('GIF360','Probabilites et modelisation de syst.discrets'));
insert into ap(values('GEI140','Appareillages et installations electriques'));
insert into ap(values('GEI145','Generation et transport'));
insert into ap(values('GEI150','Electronique de puissance'));
insert into ap(values('GEI156','Electricite industrielle'));
insert into ap(values('GEI160','Automatique industrielle'));
insert into ap(values('GEI165','Systemes electromecaniques'));
insert into ap(values('GEI170','Protection des reseaux electriques'));
insert into ap(values('GEI180','Reseaux de distribution'));
insert into ap(values('GEI702','Etude specialisee I'));
insert into ap(values('GEI703','Etude specialisee II'));
insert into ap(values('GEL822','Matiere, particules et ondes'));
insert into ap(values('GEI714','Dispositifs electroniques sur silicium et materiaux III-V'));
insert into ap(values('GEI718','Techniques de fabrication en salles blanches'));
insert into ap(values('GEI719','Microfabrication de biocapteurs'));
insert into ap(values('GEI721','Formation a la fabrication en salles blanches'));
insert into ap(values('GEI725','Principes de base et applications des lasers'));
insert into ap(values('GEI795','Mesures et qualite de logiciels'));
insert into ap(values('GEI729','Technologies et procedes de micro et nanofabrication'));
insert into ap(values('GEI734','Interfaces personne-systeme'));
insert into ap(values('GEI738','Systemes devenements discrets distribues'));
insert into ap(values('GEI741','Intelligence integree pour robots mobiles'));
insert into ap(values('GEI744','Commande de robots redondants'));
insert into ap(values('GEI745','Modelisation de robots manipulateurs'));
insert into ap(values('GEL341','Elements circuits courant alterna. trans. pui.'));
insert into ap(values('GEI755','Traitement de la parole et de laudio'));
insert into ap(values('GEL213','Electronique analogique et composants'));
insert into ap(values('GEL242','Analyse et representation de donnees scientifiques'));
insert into ap(values('GEL265','Numerisation de signaux analogiques'));
insert into ap(values('GEL402','Conception dun systeme numerique'));
insert into ap(values('GEL412','Traitement numerique des signaux'));
insert into ap(values('GEL442','Logique programmable et interfaces'));
insert into ap(values('GEL702','Projet majeur en energie electrique I'));
insert into ap(values('GEN200','Conception dun systeme electronique et informatique'));
insert into ap(values('GEN211','Mathematiques des signaux e  temps continu'));
insert into ap(values('GEN220','Systemes numeriques combinatoires'));
insert into ap(values('GEN225','Systemes numeriques sequentiels'));
insert into ap(values('GEN230','Electronique analogique I'));
insert into ap(values('GEN260','Mathematiques discretes I'));
insert into ap(values('GEN265','Mathematiques discretes II'));
insert into ap(values('GEN272','Ingenierie durable et evaluation des impacts environnementaux'));
insert into ap(values('GEN420','Mathematiques des circuits logiques'));
insert into ap(values('GEN430','Circuits logiques'));
insert into ap(values('GEN490','Innovation et creation de produits'));
insert into ap(values('GEN700','Analyse economique en ingenierie'));
insert into ap(values('GIF242','Concepts avances en programmation orientee objet'));
insert into ap(values('GIF270','Structures de donnees et complexite'));
insert into ap(values('GIF310','Architecture et organisation des ordinateurs'));
insert into ap(values('GIF340','elements de compilation'));
insert into ap(values('GIF402','Conception dun systeme ordine'));
insert into ap(values('GIF470','Physique des portes logiques'));
insert into ap(values('GIF650','Transmission de linformation'));
insert into ap(values('GIF825','Calcul et informatique quantiques'));
insert into ap(values('GIF692','Physique des ondes'));
insert into ap(values('GEN400','Ingenieur et societe'));
insert into ap(values('GEI724','Optique integree et capteurs photoniques'));
insert into ap(values('GEN242','Concepts avances en programmation orientee objet'));
insert into ap(values('GEI756','Processus aleatoires'));
insert into ap(values('GEI760','Techniques avancees de cryptographie'));
insert into ap(values('GEI761','Telematique et protocoles securises'));
insert into ap(values('GEI762','Securite des systemes informatiques'));
insert into ap(values('GEI769','Physique des composants microelectroniques'));
insert into ap(values('GEI777','Mecanique quantique pour ingenieurs'));
insert into ap(values('GEI780','Modelisation des signaux numeriques'));
insert into ap(values('GEI781','Quantification des signaux'));
insert into ap(values('GEI784','Machine synchrone et traction electrique'));
insert into ap(values('GEI786','Modeles et commande de vehicules electriques'));
insert into ap(values('GEI787','Techniques avancees en analyse'));
insert into ap(values('GEI788','Conception de circuits imprimes multicouches'));
insert into ap(values('GEI789','Conception de circuits electroniques complexes'));
insert into ap(values('GEI793','Communications vehiculaires'));
insert into ap(values('GEI804','Projet de developpement en genie informatique I'));
insert into ap(values('GEI820','Commande multivariable II'));
insert into ap(values('GEI911','Bases en conception et en gestion de projet technologique'));
insert into ap(values('GEL452','Microcontroleurs'));
insert into ap(values('GEI299','Conception et gestion pour projets techno.'));
insert into ap(values('GEI175','Electrical Power Generation IGEE418'));
insert into ap(values('GEL260','Filtrage analogique'));
insert into ap(values('GIN661','Stage I en genie electrique'));
insert into ap(values('GEI895','Conception de systemes intelligents'));
insert into ap(values('GEN550','Impacts ethiques du developpement technologique en ingenierie'));
insert into ap(values('GIN654','Stage IV en genie informatique'));
insert into ap(values('GIN652','Stage II en genie informatique'));
insert into ap(values('GIN651','Stage I en genie informatique'));
insert into ap(values('GEL362','Thermique'));
insert into ap(values('GEN800','Formation professionnelle en genie'));
insert into ap(values('GIF501','Conception dun systeme de simulation'));
insert into ap(values('GEN145','Atelier de programmation'));
insert into ap(values('GEI808','Essai'));
insert into ap(values('GEI794','Principes avances de conception par objets'));
insert into ap(values('GEL655','Physique des composants semiconducteurs'));
insert into ap(values('GEN135','Circuits electriques I'));
insert into ap(values('GEN181','Modelisation 3'));
insert into ap(values('GIF591','Probabilites et statistiques'));
insert into ap(values('GIN663','Stage III en genie electrique'));
insert into ap(values('GIN653','Stage III en genie informatique'));
insert into ap(values('GEN280','Conception securitaire'));
insert into ap(values('GIF480','Systeme sensoriel chez lhumain'));
insert into ap(values('GIN664','Stage IV en genie electrique'));
insert into ap(values('GIN665','Stage V en genie electrique'));
insert into ap(values('GIN662','Stage II en genie electrique'));
insert into ap(values('GEI185','Comportement des reseaux electriques'));
insert into ap(values('GEI790','Intelligence artificielle formalisable'));
insert into ap(values('GEI791','Intelligence artificielle probabiliste'));
insert into ap(values('GIF333','Theorie des groupes et algebre abstraite en ingenierie'));
insert into ap(values('GEI792','Intelligence artificielle bio-inspiree'));
insert into ap(values('GEI796','Pratiques dans les developpements agiles'));
insert into ap(values('GEI799','Verification de logiciels'));
insert into ap(values('GIF390','Systemes informatiques repartis'));
insert into ap(values('GEI199','Circuits logiques et electroniques numeriques'));


insert into author(values (1,'Gilbert SYBILLE'));
insert into author(values (2,'Théodore WILDI'));
insert into author(values (3,'Siddhartha RAO'));
insert into author(values (4,'J. Duncan Glover'));
insert into author(values (5,'Thomas Overbye'));
insert into author(values (6,'Mulukutla Sarma'));

insert into format(values (1, 'Papier', 1));
insert into format(values (2, 'PDF', 2));
insert into format(values (3, 'Epub', 2));
insert into format(values (4, 'site Internet', 2));
insert into format(values (5, 'Person', 2));

insert into typeformat(values (1,'Papier'));
insert into typeformat(values (2,'Digital'));

insert into editor(values (1,'PUL - Presses U. de Laval'));
insert into editor(values (2,'SAMS'));

insert into language(values ( 1, 'Français'));
insert into language(values ( 2, 'Anglais'));
insert into language(values ( 3, 'Espagnol'));
insert into language(values ( 4, 'Portugais'));
insert into language(values ( 5, 'Allemand'));

insert into image(values (1, '/images/9780789757746.jpg'));
insert into image(values (2, '/images/9782763781853.jpg'));
insert into image(values(3,'/images/9781305632134.jpg'));
insert into image(values(4,'/images/9782100809356.jpg'));
insert into image(values(5,'/images/9781943153183.jpg'));
insert into image(values(6,'/images/None.jpg'));
insert into image(values(7,'/images/9782744075216.jpg'));
insert into image(values(8,'/images/9780190853464.jpg'));
insert into image(values(9,'/images/9782890943377.jpg'));
insert into image(values(10,'/images/9781578201242.jpg'));
insert into image(values(11,'/images/9782100555642.jpg'));
insert into image(values(12,'/images/9780131194571.jpg'));
insert into image(values(13,'/images/9782744074660.jpg'));
insert into image(values(14,'/images/9782729857042.jpg'));
insert into image(values(15,'/images/9781590282571.jpg'));
insert into image(values(16,'/images/9781627056205.jpg'));
insert into image(values(18,'/images/9780134460093.jpg'));
insert into image(values(19,'/images/9780124077263.jpg'));
insert into image(values(20,'/images/9791092564358.jpg'));
insert into image(values(21,'/images/9780137027415.jpg'));
insert into image(values(22,'/images/9791092564297.jpg'));
insert into image(values(23,'/images/9780136156734.jpg'));
insert into image(values(24,'/images/9782890943377.jpg'));
insert into image(values(25,'/images/9781846286414.jpg'));
insert into image(values(26,'/images/9780128094747.jpg'));
insert into image(values(27,'/images/9780974193601.jpg'));
insert into image(values(28,'/images/9782766108206.jpg'));



insert into associated_SigleToProgram(values ('GEI100',1));
insert into associated_SigleToProgram(values ('GEI105',1));
insert into associated_SigleToProgram(values ('GEI120',1));
insert into associated_SigleToProgram(values ('GEI130',1));
insert into associated_SigleToProgram(values ('GEI140',1));
insert into associated_SigleToProgram(values ('GEI145',1));
insert into associated_SigleToProgram(values ('GEI150',1));
insert into associated_SigleToProgram(values ('GEI155',1));
insert into associated_SigleToProgram(values ('GEI156',1));
insert into associated_SigleToProgram(values ('GEI160',1));
insert into associated_SigleToProgram(values ('GEI165',1));
insert into associated_SigleToProgram(values ('GEI166',1));
insert into associated_SigleToProgram(values ('GEI170',1));
insert into associated_SigleToProgram(values ('GEI175',1));
insert into associated_SigleToProgram(values ('GEI180',1));
insert into associated_SigleToProgram(values ('GEI185',1));
insert into associated_SigleToProgram(values ('GEI199',1));
insert into associated_SigleToProgram(values ('GEI200',1));
insert into associated_SigleToProgram(values ('GEI205',1));
insert into associated_SigleToProgram(values ('GEI210',1));
insert into associated_SigleToProgram(values ('GEI215',1));
insert into associated_SigleToProgram(values ('GEI220',1));
insert into associated_SigleToProgram(values ('GEI240',1));
insert into associated_SigleToProgram(values ('GEI299',1));
insert into associated_SigleToProgram(values ('GEI301',1));
insert into associated_SigleToProgram(values ('GEI335',1));
insert into associated_SigleToProgram(values ('GEI340',1));
insert into associated_SigleToProgram(values ('GEI346',1));
insert into associated_SigleToProgram(values ('GEI355',1));
insert into associated_SigleToProgram(values ('GEI410',1));
insert into associated_SigleToProgram(values ('GEI415',1));
insert into associated_SigleToProgram(values ('GEI430',1));
insert into associated_SigleToProgram(values ('GEI431',1));
insert into associated_SigleToProgram(values ('GEI435',1));
insert into associated_SigleToProgram(values ('GEI437',1));
insert into associated_SigleToProgram(values ('GEI441',1));
insert into associated_SigleToProgram(values ('GEI442',1));
insert into associated_SigleToProgram(values ('GEI443',1));
insert into associated_SigleToProgram(values ('GEI446',1));
insert into associated_SigleToProgram(values ('GEI448',1));
insert into associated_SigleToProgram(values ('GEI450',1));
insert into associated_SigleToProgram(values ('GEI452',1));
insert into associated_SigleToProgram(values ('GEI455',1));
insert into associated_SigleToProgram(values ('GEI457',1));
insert into associated_SigleToProgram(values ('GEI460',1));
insert into associated_SigleToProgram(values ('GEI465',1));
insert into associated_SigleToProgram(values ('GEI500',1));
insert into associated_SigleToProgram(values ('GEI540',1));
insert into associated_SigleToProgram(values ('GEI600',1));
insert into associated_SigleToProgram(values ('GEI605',1));
insert into associated_SigleToProgram(values ('GEI610',1));
insert into associated_SigleToProgram(values ('GEI615',1));
insert into associated_SigleToProgram(values ('GEI640',1));
insert into associated_SigleToProgram(values ('GEI701',1));
insert into associated_SigleToProgram(values ('GEI702',1));
insert into associated_SigleToProgram(values ('GEI703',1));
insert into associated_SigleToProgram(values ('GEI705',1));
insert into associated_SigleToProgram(values ('GEI710',1));
insert into associated_SigleToProgram(values ('GEI712',1));
insert into associated_SigleToProgram(values ('GEI714',1));
insert into associated_SigleToProgram(values ('GEI715',1));
insert into associated_SigleToProgram(values ('GEI717',1));
insert into associated_SigleToProgram(values ('GEI718',1));
insert into associated_SigleToProgram(values ('GEI719',1));
insert into associated_SigleToProgram(values ('GEI720',1));
insert into associated_SigleToProgram(values ('GEI721',1));
insert into associated_SigleToProgram(values ('GEI722',1));
insert into associated_SigleToProgram(values ('GEI723',1));
insert into associated_SigleToProgram(values ('GEI724',1));
insert into associated_SigleToProgram(values ('GEI725',1));
insert into associated_SigleToProgram(values ('GEI726',1));
insert into associated_SigleToProgram(values ('GEI727',1));
insert into associated_SigleToProgram(values ('GEI728',1));
insert into associated_SigleToProgram(values ('GEI729',1));
insert into associated_SigleToProgram(values ('GEI730',1));
insert into associated_SigleToProgram(values ('GEI734',1));
insert into associated_SigleToProgram(values ('GEI735',1));
insert into associated_SigleToProgram(values ('GEI736',1));
insert into associated_SigleToProgram(values ('GEI738',1));
insert into associated_SigleToProgram(values ('GEI739',1));
insert into associated_SigleToProgram(values ('GEI740',1));
insert into associated_SigleToProgram(values ('GEI741',1));
insert into associated_SigleToProgram(values ('GEI742',1));
insert into associated_SigleToProgram(values ('GEI744',1));
insert into associated_SigleToProgram(values ('GEI745',1));
insert into associated_SigleToProgram(values ('GEI746',1));
insert into associated_SigleToProgram(values ('GEI747',1));
insert into associated_SigleToProgram(values ('GEI748',1));
insert into associated_SigleToProgram(values ('GEI749',1));
insert into associated_SigleToProgram(values ('GEI751',1));
insert into associated_SigleToProgram(values ('GEI752',1));
insert into associated_SigleToProgram(values ('GEI754',1));
insert into associated_SigleToProgram(values ('GEI755',1));
insert into associated_SigleToProgram(values ('GEI756',1));
insert into associated_SigleToProgram(values ('GEI759',1));
insert into associated_SigleToProgram(values ('GEI760',1));
insert into associated_SigleToProgram(values ('GEI761',1));
insert into associated_SigleToProgram(values ('GEI762',1));
insert into associated_SigleToProgram(values ('GEI763',1));
insert into associated_SigleToProgram(values ('GEI764',1));
insert into associated_SigleToProgram(values ('GEI765',1));
insert into associated_SigleToProgram(values ('GEI766',1));
insert into associated_SigleToProgram(values ('GEI767',1));
insert into associated_SigleToProgram(values ('GEI768',1));
insert into associated_SigleToProgram(values ('GEI769',1));
insert into associated_SigleToProgram(values ('GEI770',1));
insert into associated_SigleToProgram(values ('GEI771',1));
insert into associated_SigleToProgram(values ('GEI772',1));
insert into associated_SigleToProgram(values ('GEI773',1));
insert into associated_SigleToProgram(values ('GEI774',1));
insert into associated_SigleToProgram(values ('GEI775',1));
insert into associated_SigleToProgram(values ('GEI776',1));
insert into associated_SigleToProgram(values ('GEI777',1));
insert into associated_SigleToProgram(values ('GEI778',1));
insert into associated_SigleToProgram(values ('GEI779',1));
insert into associated_SigleToProgram(values ('GEI780',1));
insert into associated_SigleToProgram(values ('GEI781',1));
insert into associated_SigleToProgram(values ('GEI783',1));
insert into associated_SigleToProgram(values ('GEI784',1));
insert into associated_SigleToProgram(values ('GEI785',1));
insert into associated_SigleToProgram(values ('GEI786',1));
insert into associated_SigleToProgram(values ('GEI787',1));
insert into associated_SigleToProgram(values ('GEI788',1));
insert into associated_SigleToProgram(values ('GEI789',1));
insert into associated_SigleToProgram(values ('GEI790',1));
insert into associated_SigleToProgram(values ('GEI791',1));
insert into associated_SigleToProgram(values ('GEI792',1));
insert into associated_SigleToProgram(values ('GEI793',1));
insert into associated_SigleToProgram(values ('GEI794',1));
insert into associated_SigleToProgram(values ('GEI795',1));
insert into associated_SigleToProgram(values ('GEI796',1));
insert into associated_SigleToProgram(values ('GEI797',1));
insert into associated_SigleToProgram(values ('GEI798',1));
insert into associated_SigleToProgram(values ('GEI799',1));
insert into associated_SigleToProgram(values ('GEI801',1));
insert into associated_SigleToProgram(values ('GEI803',1));
insert into associated_SigleToProgram(values ('GEI804',1));
insert into associated_SigleToProgram(values ('GEI805',1));
insert into associated_SigleToProgram(values ('GEI806',1));
insert into associated_SigleToProgram(values ('GEI807',1));
insert into associated_SigleToProgram(values ('GEI808',1));
insert into associated_SigleToProgram(values ('GEI810',1));
insert into associated_SigleToProgram(values ('GEI815',1));
insert into associated_SigleToProgram(values ('GEI820',1));
insert into associated_SigleToProgram(values ('GEI822',1));
insert into associated_SigleToProgram(values ('GEI825',1));
insert into associated_SigleToProgram(values ('GEI845',1));
insert into associated_SigleToProgram(values ('GEI877',1));
insert into associated_SigleToProgram(values ('GEI883',1));
insert into associated_SigleToProgram(values ('GEI890',1));
insert into associated_SigleToProgram(values ('GEI895',1));
insert into associated_SigleToProgram(values ('GEI911',1));
insert into associated_SigleToProgram(values ('GEI100',2));
insert into associated_SigleToProgram(values ('GEI105',2));
insert into associated_SigleToProgram(values ('GEI120',2));
insert into associated_SigleToProgram(values ('GEI130',2));
insert into associated_SigleToProgram(values ('GEI140',2));
insert into associated_SigleToProgram(values ('GEI145',2));
insert into associated_SigleToProgram(values ('GEI150',2));
insert into associated_SigleToProgram(values ('GEI155',2));
insert into associated_SigleToProgram(values ('GEI156',2));
insert into associated_SigleToProgram(values ('GEI160',2));
insert into associated_SigleToProgram(values ('GEI165',2));
insert into associated_SigleToProgram(values ('GEI166',2));
insert into associated_SigleToProgram(values ('GEI170',2));
insert into associated_SigleToProgram(values ('GEI175',2));
insert into associated_SigleToProgram(values ('GEI180',2));
insert into associated_SigleToProgram(values ('GEI185',2));
insert into associated_SigleToProgram(values ('GEI199',2));
insert into associated_SigleToProgram(values ('GEI200',2));
insert into associated_SigleToProgram(values ('GEI205',2));
insert into associated_SigleToProgram(values ('GEI210',2));
insert into associated_SigleToProgram(values ('GEI215',2));
insert into associated_SigleToProgram(values ('GEI220',2));
insert into associated_SigleToProgram(values ('GEI240',2));
insert into associated_SigleToProgram(values ('GEI299',2));
insert into associated_SigleToProgram(values ('GEI301',2));
insert into associated_SigleToProgram(values ('GEI335',2));
insert into associated_SigleToProgram(values ('GEI340',2));
insert into associated_SigleToProgram(values ('GEI346',2));
insert into associated_SigleToProgram(values ('GEI355',2));
insert into associated_SigleToProgram(values ('GEI410',2));
insert into associated_SigleToProgram(values ('GEI415',2));
insert into associated_SigleToProgram(values ('GEI430',2));
insert into associated_SigleToProgram(values ('GEI431',2));
insert into associated_SigleToProgram(values ('GEI435',2));
insert into associated_SigleToProgram(values ('GEI437',2));
insert into associated_SigleToProgram(values ('GEI441',2));
insert into associated_SigleToProgram(values ('GEI442',2));
insert into associated_SigleToProgram(values ('GEI443',2));
insert into associated_SigleToProgram(values ('GEI446',2));
insert into associated_SigleToProgram(values ('GEI448',2));
insert into associated_SigleToProgram(values ('GEI450',2));
insert into associated_SigleToProgram(values ('GEI452',2));
insert into associated_SigleToProgram(values ('GEI455',2));
insert into associated_SigleToProgram(values ('GEI457',2));
insert into associated_SigleToProgram(values ('GEI460',2));
insert into associated_SigleToProgram(values ('GEI465',2));
insert into associated_SigleToProgram(values ('GEI500',2));
insert into associated_SigleToProgram(values ('GEI540',2));
insert into associated_SigleToProgram(values ('GEI600',2));
insert into associated_SigleToProgram(values ('GEI605',2));
insert into associated_SigleToProgram(values ('GEI610',2));
insert into associated_SigleToProgram(values ('GEI615',2));
insert into associated_SigleToProgram(values ('GEI640',2));
insert into associated_SigleToProgram(values ('GEI701',2));
insert into associated_SigleToProgram(values ('GEI702',2));
insert into associated_SigleToProgram(values ('GEI703',2));
insert into associated_SigleToProgram(values ('GEI705',2));
insert into associated_SigleToProgram(values ('GEI710',2));
insert into associated_SigleToProgram(values ('GEI712',2));
insert into associated_SigleToProgram(values ('GEI714',2));
insert into associated_SigleToProgram(values ('GEI715',2));
insert into associated_SigleToProgram(values ('GEI717',2));
insert into associated_SigleToProgram(values ('GEI718',2));
insert into associated_SigleToProgram(values ('GEI719',2));
insert into associated_SigleToProgram(values ('GEI720',2));
insert into associated_SigleToProgram(values ('GEI721',2));
insert into associated_SigleToProgram(values ('GEI722',2));
insert into associated_SigleToProgram(values ('GEI724',2));
insert into associated_SigleToProgram(values ('GEI725',2));
insert into associated_SigleToProgram(values ('GEI726',2));
insert into associated_SigleToProgram(values ('GEI727',2));
insert into associated_SigleToProgram(values ('GEI728',2));
insert into associated_SigleToProgram(values ('GEI729',2));
insert into associated_SigleToProgram(values ('GEI730',2));
insert into associated_SigleToProgram(values ('GEI734',2));
insert into associated_SigleToProgram(values ('GEI735',2));
insert into associated_SigleToProgram(values ('GEI736',2));
insert into associated_SigleToProgram(values ('GEI738',2));
insert into associated_SigleToProgram(values ('GEI739',2));
insert into associated_SigleToProgram(values ('GEI740',2));
insert into associated_SigleToProgram(values ('GEI741',2));
insert into associated_SigleToProgram(values ('GEI742',2));
insert into associated_SigleToProgram(values ('GEI744',2));
insert into associated_SigleToProgram(values ('GEI745',2));
insert into associated_SigleToProgram(values ('GEI746',2));
insert into associated_SigleToProgram(values ('GEI747',2));
insert into associated_SigleToProgram(values ('GEI748',2));
insert into associated_SigleToProgram(values ('GEI749',2));
insert into associated_SigleToProgram(values ('GEI751',2));
insert into associated_SigleToProgram(values ('GEI752',2));
insert into associated_SigleToProgram(values ('GEI754',2));
insert into associated_SigleToProgram(values ('GEI755',2));
insert into associated_SigleToProgram(values ('GEI756',2));
insert into associated_SigleToProgram(values ('GEI759',2));
insert into associated_SigleToProgram(values ('GEI760',2));
insert into associated_SigleToProgram(values ('GEI761',2));
insert into associated_SigleToProgram(values ('GEI762',2));
insert into associated_SigleToProgram(values ('GEI763',2));
insert into associated_SigleToProgram(values ('GEI764',2));
insert into associated_SigleToProgram(values ('GEI765',2));
insert into associated_SigleToProgram(values ('GEI766',2));
insert into associated_SigleToProgram(values ('GEI767',2));
insert into associated_SigleToProgram(values ('GEI768',2));
insert into associated_SigleToProgram(values ('GEI769',2));
insert into associated_SigleToProgram(values ('GEI770',2));
insert into associated_SigleToProgram(values ('GEI771',2));
insert into associated_SigleToProgram(values ('GEI772',2));
insert into associated_SigleToProgram(values ('GEI773',2));
insert into associated_SigleToProgram(values ('GEI774',2));
insert into associated_SigleToProgram(values ('GEI775',2));
insert into associated_SigleToProgram(values ('GEI776',2));
insert into associated_SigleToProgram(values ('GEI777',2));
insert into associated_SigleToProgram(values ('GEI778',2));
insert into associated_SigleToProgram(values ('GEI779',2));
insert into associated_SigleToProgram(values ('GEI780',2));
insert into associated_SigleToProgram(values ('GEI781',2));
insert into associated_SigleToProgram(values ('GEI783',2));
insert into associated_SigleToProgram(values ('GEI784',2));
insert into associated_SigleToProgram(values ('GEI785',2));
insert into associated_SigleToProgram(values ('GEI786',2));
insert into associated_SigleToProgram(values ('GEI787',2));
insert into associated_SigleToProgram(values ('GEI788',2));
insert into associated_SigleToProgram(values ('GEI789',2));
insert into associated_SigleToProgram(values ('GEI790',2));
insert into associated_SigleToProgram(values ('GEI791',2));
insert into associated_SigleToProgram(values ('GEI792',2));
insert into associated_SigleToProgram(values ('GEI793',2));
insert into associated_SigleToProgram(values ('GEI794',2));
insert into associated_SigleToProgram(values ('GEI795',2));
insert into associated_SigleToProgram(values ('GEI796',2));
insert into associated_SigleToProgram(values ('GEI797',2));
insert into associated_SigleToProgram(values ('GEI798',2));
insert into associated_SigleToProgram(values ('GEI799',2));
insert into associated_SigleToProgram(values ('GEI801',2));
insert into associated_SigleToProgram(values ('GEI803',2));
insert into associated_SigleToProgram(values ('GEI804',2));
insert into associated_SigleToProgram(values ('GEI805',2));
insert into associated_SigleToProgram(values ('GEI806',2));
insert into associated_SigleToProgram(values ('GEI807',2));
insert into associated_SigleToProgram(values ('GEI808',2));
insert into associated_SigleToProgram(values ('GEI810',2));
insert into associated_SigleToProgram(values ('GEI815',2));
insert into associated_SigleToProgram(values ('GEI820',2));
insert into associated_SigleToProgram(values ('GEI822',2));
insert into associated_SigleToProgram(values ('GEI825',2));
insert into associated_SigleToProgram(values ('GEI845',2));
insert into associated_SigleToProgram(values ('GEI877',2));
insert into associated_SigleToProgram(values ('GEI883',2));
insert into associated_SigleToProgram(values ('GEI890',2));
insert into associated_SigleToProgram(values ('GEI895',2));
insert into associated_SigleToProgram(values ('GEI911',2));
insert into associated_SigleToProgram(values ('GEL201',2));
insert into associated_SigleToProgram(values ('GEL211',2));
insert into associated_SigleToProgram(values ('GEL212',2));
insert into associated_SigleToProgram(values ('GEL213',2));
insert into associated_SigleToProgram(values ('GEL242',2));
insert into associated_SigleToProgram(values ('GEL260',2));
insert into associated_SigleToProgram(values ('GEL265',2));
insert into associated_SigleToProgram(values ('GEL301',2));
insert into associated_SigleToProgram(values ('GEL302',2));
insert into associated_SigleToProgram(values ('GEL311',2));
insert into associated_SigleToProgram(values ('GEL315',2));
insert into associated_SigleToProgram(values ('GEL320',2));
insert into associated_SigleToProgram(values ('GEL331',2));
insert into associated_SigleToProgram(values ('GEL335',2));
insert into associated_SigleToProgram(values ('GEL340',2));
insert into associated_SigleToProgram(values ('GEL341',2));
insert into associated_SigleToProgram(values ('GEL342',2));
insert into associated_SigleToProgram(values ('GEL345',2));
insert into associated_SigleToProgram(values ('GEL350',2));
insert into associated_SigleToProgram(values ('GEL355',2));
insert into associated_SigleToProgram(values ('GEL361',2));
insert into associated_SigleToProgram(values ('GEL362',2));
insert into associated_SigleToProgram(values ('GEL370',2));
insert into associated_SigleToProgram(values ('GEL401',2));
insert into associated_SigleToProgram(values ('GEL402',2));
insert into associated_SigleToProgram(values ('GEL412',2));
insert into associated_SigleToProgram(values ('GEL420',2));
insert into associated_SigleToProgram(values ('GEL421',2));
insert into associated_SigleToProgram(values ('GEL431',2));
insert into associated_SigleToProgram(values ('GEL432',2));
insert into associated_SigleToProgram(values ('GEL442',2));
insert into associated_SigleToProgram(values ('GEL450',2));
insert into associated_SigleToProgram(values ('GEL452',2));
insert into associated_SigleToProgram(values ('GEL500',2));
insert into associated_SigleToProgram(values ('GEL511',2));
insert into associated_SigleToProgram(values ('GEL520',2));
insert into associated_SigleToProgram(values ('GEL521',2));
insert into associated_SigleToProgram(values ('GEL530',2));
insert into associated_SigleToProgram(values ('GEL601',2));
insert into associated_SigleToProgram(values ('GEL610',2));
insert into associated_SigleToProgram(values ('GEL611',2));
insert into associated_SigleToProgram(values ('GEL620',2));
insert into associated_SigleToProgram(values ('GEL625',2));
insert into associated_SigleToProgram(values ('GEL630',2));
insert into associated_SigleToProgram(values ('GEL641',2));
insert into associated_SigleToProgram(values ('GEL650',2));
insert into associated_SigleToProgram(values ('GEL651',2));
insert into associated_SigleToProgram(values ('GEL655',2));
insert into associated_SigleToProgram(values ('GEL660',2));
insert into associated_SigleToProgram(values ('GEL661',2));
insert into associated_SigleToProgram(values ('GEL662',2));
insert into associated_SigleToProgram(values ('GEL665',2));
insert into associated_SigleToProgram(values ('GEL701',2));
insert into associated_SigleToProgram(values ('GEL702',2));
insert into associated_SigleToProgram(values ('GEL801',2));
insert into associated_SigleToProgram(values ('GEL802',2));
insert into associated_SigleToProgram(values ('GEL803',2));
insert into associated_SigleToProgram(values ('GEL822',2));
insert into associated_SigleToProgram(values ('GEN101',1));
insert into associated_SigleToProgram(values ('GEN111',1));
insert into associated_SigleToProgram(values ('GEN122',1));
insert into associated_SigleToProgram(values ('GEN123',1));
insert into associated_SigleToProgram(values ('GEN124',1));
insert into associated_SigleToProgram(values ('GEN131',1));
insert into associated_SigleToProgram(values ('GEN133',1));
insert into associated_SigleToProgram(values ('GEN134',1));
insert into associated_SigleToProgram(values ('GEN135',1));
insert into associated_SigleToProgram(values ('GEN136',1));
insert into associated_SigleToProgram(values ('GEN137',1));
insert into associated_SigleToProgram(values ('GEN143',1));
insert into associated_SigleToProgram(values ('GEN144',1));
insert into associated_SigleToProgram(values ('GEN145',1));
insert into associated_SigleToProgram(values ('GEN146',1));
insert into associated_SigleToProgram(values ('GEN150',1));
insert into associated_SigleToProgram(values ('GEN160',1));
insert into associated_SigleToProgram(values ('GEN170',1));
insert into associated_SigleToProgram(values ('GEN180',1));
insert into associated_SigleToProgram(values ('GEN181',1));
insert into associated_SigleToProgram(values ('GEN182',1));
insert into associated_SigleToProgram(values ('GEN200',1));
insert into associated_SigleToProgram(values ('GEN210',1));
insert into associated_SigleToProgram(values ('GEN211',1));
insert into associated_SigleToProgram(values ('GEN220',1));
insert into associated_SigleToProgram(values ('GEN225',1));
insert into associated_SigleToProgram(values ('GEN230',1));
insert into associated_SigleToProgram(values ('GEN240',1));
insert into associated_SigleToProgram(values ('GEN241',1));
insert into associated_SigleToProgram(values ('GEN242',1));
insert into associated_SigleToProgram(values ('GEN260',1));
insert into associated_SigleToProgram(values ('GEN265',1));
insert into associated_SigleToProgram(values ('GEN270',1));
insert into associated_SigleToProgram(values ('GEN271',1));
insert into associated_SigleToProgram(values ('GEN272',1));
insert into associated_SigleToProgram(values ('GEN280',1));
insert into associated_SigleToProgram(values ('GEN400',1));
insert into associated_SigleToProgram(values ('GEN410',1));
insert into associated_SigleToProgram(values ('GEN420',1));
insert into associated_SigleToProgram(values ('GEN430',1));
insert into associated_SigleToProgram(values ('GEN440',1));
insert into associated_SigleToProgram(values ('GEN441',1));
insert into associated_SigleToProgram(values ('GEN450',1));
insert into associated_SigleToProgram(values ('GEN490',1));
insert into associated_SigleToProgram(values ('GEN501',1));
insert into associated_SigleToProgram(values ('GEN502',1));
insert into associated_SigleToProgram(values ('GEN550',1));
insert into associated_SigleToProgram(values ('GEN600',1));
insert into associated_SigleToProgram(values ('GEN650',1));
insert into associated_SigleToProgram(values ('GEN700',1));
insert into associated_SigleToProgram(values ('GEN701',1));
insert into associated_SigleToProgram(values ('GEN800',1));
insert into associated_SigleToProgram(values ('GEN801',1));
insert into associated_SigleToProgram(values ('GEN101',2));
insert into associated_SigleToProgram(values ('GEN111',2));
insert into associated_SigleToProgram(values ('GEN122',2));
insert into associated_SigleToProgram(values ('GEN123',2));
insert into associated_SigleToProgram(values ('GEN124',2));
insert into associated_SigleToProgram(values ('GEN131',2));
insert into associated_SigleToProgram(values ('GEN133',2));
insert into associated_SigleToProgram(values ('GEN134',2));
insert into associated_SigleToProgram(values ('GEN135',2));
insert into associated_SigleToProgram(values ('GEN136',2));
insert into associated_SigleToProgram(values ('GEN137',2));
insert into associated_SigleToProgram(values ('GEN143',2));
insert into associated_SigleToProgram(values ('GEN144',2));
insert into associated_SigleToProgram(values ('GEN145',2));
insert into associated_SigleToProgram(values ('GEN146',2));
insert into associated_SigleToProgram(values ('GEN150',2));
insert into associated_SigleToProgram(values ('GEN160',2));
insert into associated_SigleToProgram(values ('GEN170',2));
insert into associated_SigleToProgram(values ('GEN180',2));
insert into associated_SigleToProgram(values ('GEN181',2));
insert into associated_SigleToProgram(values ('GEN182',2));
insert into associated_SigleToProgram(values ('GEN200',2));
insert into associated_SigleToProgram(values ('GEN210',2));
insert into associated_SigleToProgram(values ('GEN211',2));
insert into associated_SigleToProgram(values ('GEN220',2));
insert into associated_SigleToProgram(values ('GEN225',2));
insert into associated_SigleToProgram(values ('GEN230',2));
insert into associated_SigleToProgram(values ('GEN240',2));
insert into associated_SigleToProgram(values ('GEN241',2));
insert into associated_SigleToProgram(values ('GEN242',2));
insert into associated_SigleToProgram(values ('GEN260',2));
insert into associated_SigleToProgram(values ('GEN265',2));
insert into associated_SigleToProgram(values ('GEN270',2));
insert into associated_SigleToProgram(values ('GEN271',2));
insert into associated_SigleToProgram(values ('GEN272',2));
insert into associated_SigleToProgram(values ('GEN280',2));
insert into associated_SigleToProgram(values ('GEN400',2));
insert into associated_SigleToProgram(values ('GEN410',2));
insert into associated_SigleToProgram(values ('GEN420',2));
insert into associated_SigleToProgram(values ('GEN430',2));
insert into associated_SigleToProgram(values ('GEN440',2));
insert into associated_SigleToProgram(values ('GEN441',2));
insert into associated_SigleToProgram(values ('GEN450',2));
insert into associated_SigleToProgram(values ('GEN490',2));
insert into associated_SigleToProgram(values ('GEN501',2));
insert into associated_SigleToProgram(values ('GEN502',2));
insert into associated_SigleToProgram(values ('GEN550',2));
insert into associated_SigleToProgram(values ('GEN600',2));
insert into associated_SigleToProgram(values ('GEN650',2));
insert into associated_SigleToProgram(values ('GEN700',2));
insert into associated_SigleToProgram(values ('GEN701',2));
insert into associated_SigleToProgram(values ('GEN800',2));
insert into associated_SigleToProgram(values ('GEN801',2));
insert into associated_SigleToProgram(values ('GEN101',3));
insert into associated_SigleToProgram(values ('GEN111',3));
insert into associated_SigleToProgram(values ('GEN122',3));
insert into associated_SigleToProgram(values ('GEN123',3));
insert into associated_SigleToProgram(values ('GEN124',3));
insert into associated_SigleToProgram(values ('GEN131',3));
insert into associated_SigleToProgram(values ('GEN133',3));
insert into associated_SigleToProgram(values ('GEN134',3));
insert into associated_SigleToProgram(values ('GEN135',3));
insert into associated_SigleToProgram(values ('GEN136',3));
insert into associated_SigleToProgram(values ('GEN137',3));
insert into associated_SigleToProgram(values ('GEN143',3));
insert into associated_SigleToProgram(values ('GEN144',3));
insert into associated_SigleToProgram(values ('GEN145',3));
insert into associated_SigleToProgram(values ('GEN146',3));
insert into associated_SigleToProgram(values ('GEN150',3));
insert into associated_SigleToProgram(values ('GEN160',3));
insert into associated_SigleToProgram(values ('GEN170',3));
insert into associated_SigleToProgram(values ('GEN180',3));
insert into associated_SigleToProgram(values ('GEN181',3));
insert into associated_SigleToProgram(values ('GEN182',3));
insert into associated_SigleToProgram(values ('GEN200',3));
insert into associated_SigleToProgram(values ('GEN210',3));
insert into associated_SigleToProgram(values ('GEN211',3));
insert into associated_SigleToProgram(values ('GEN220',3));
insert into associated_SigleToProgram(values ('GEN225',3));
insert into associated_SigleToProgram(values ('GEN230',3));
insert into associated_SigleToProgram(values ('GEN240',3));
insert into associated_SigleToProgram(values ('GEN241',3));
insert into associated_SigleToProgram(values ('GEN242',3));
insert into associated_SigleToProgram(values ('GEN260',3));
insert into associated_SigleToProgram(values ('GEN265',3));
insert into associated_SigleToProgram(values ('GEN270',3));
insert into associated_SigleToProgram(values ('GEN271',3));
insert into associated_SigleToProgram(values ('GEN272',3));
insert into associated_SigleToProgram(values ('GEN280',3));
insert into associated_SigleToProgram(values ('GEN400',3));
insert into associated_SigleToProgram(values ('GEN410',3));
insert into associated_SigleToProgram(values ('GEN420',3));
insert into associated_SigleToProgram(values ('GEN430',3));
insert into associated_SigleToProgram(values ('GEN440',3));
insert into associated_SigleToProgram(values ('GEN441',3));
insert into associated_SigleToProgram(values ('GEN450',3));
insert into associated_SigleToProgram(values ('GEN490',3));
insert into associated_SigleToProgram(values ('GEN501',3));
insert into associated_SigleToProgram(values ('GEN502',3));
insert into associated_SigleToProgram(values ('GEN550',3));
insert into associated_SigleToProgram(values ('GEN600',3));
insert into associated_SigleToProgram(values ('GEN650',3));
insert into associated_SigleToProgram(values ('GEN700',3));
insert into associated_SigleToProgram(values ('GEN701',3));
insert into associated_SigleToProgram(values ('GEN800',3));
insert into associated_SigleToProgram(values ('GEN801',3));

insert into associated_SigleToProgram(values ('GIF201',1));
insert into associated_SigleToProgram(values ('GIF230',1));
insert into associated_SigleToProgram(values ('GIF242',1));
insert into associated_SigleToProgram(values ('GIF261',1));
insert into associated_SigleToProgram(values ('GIF270',1));
insert into associated_SigleToProgram(values ('GIF301',1));
insert into associated_SigleToProgram(values ('GIF302',1));
insert into associated_SigleToProgram(values ('GIF310',1));
insert into associated_SigleToProgram(values ('GIF320',1));
insert into associated_SigleToProgram(values ('GIF331',1));
insert into associated_SigleToProgram(values ('GIF332',1));
insert into associated_SigleToProgram(values ('GIF333',1));
insert into associated_SigleToProgram(values ('GIF340',1));
insert into associated_SigleToProgram(values ('GIF350',1));
insert into associated_SigleToProgram(values ('GIF360',1));
insert into associated_SigleToProgram(values ('GIF362',1));
insert into associated_SigleToProgram(values ('GIF370',1));
insert into associated_SigleToProgram(values ('GIF371',1));
insert into associated_SigleToProgram(values ('GIF380',1));
insert into associated_SigleToProgram(values ('GIF390',1));
insert into associated_SigleToProgram(values ('GIF391',1));
insert into associated_SigleToProgram(values ('GIF400',1));
insert into associated_SigleToProgram(values ('GIF401',1));
insert into associated_SigleToProgram(values ('GIF402',1));
insert into associated_SigleToProgram(values ('GIF421',1));
insert into associated_SigleToProgram(values ('GIF442',1));
insert into associated_SigleToProgram(values ('GIF443',1));
insert into associated_SigleToProgram(values ('GIF450',1));
insert into associated_SigleToProgram(values ('GIF460',1));
insert into associated_SigleToProgram(values ('GIF470',1));
insert into associated_SigleToProgram(values ('GIF480',1));
insert into associated_SigleToProgram(values ('GIF501',1));
insert into associated_SigleToProgram(values ('GIF510',1));
insert into associated_SigleToProgram(values ('GIF521',1));
insert into associated_SigleToProgram(values ('GIF530',1));
insert into associated_SigleToProgram(values ('GIF540',1));
insert into associated_SigleToProgram(values ('GIF550',1));
insert into associated_SigleToProgram(values ('GIF560',1));
insert into associated_SigleToProgram(values ('GIF570',1));
insert into associated_SigleToProgram(values ('GIF580',1));
insert into associated_SigleToProgram(values ('GIF590',1));
insert into associated_SigleToProgram(values ('GIF591',1));
insert into associated_SigleToProgram(values ('GIF592',1));
insert into associated_SigleToProgram(values ('GIF600',1));
insert into associated_SigleToProgram(values ('GIF601',1));
insert into associated_SigleToProgram(values ('GIF611',1));
insert into associated_SigleToProgram(values ('GIF620',1));
insert into associated_SigleToProgram(values ('GIF630',1));
insert into associated_SigleToProgram(values ('GIF640',1));
insert into associated_SigleToProgram(values ('GIF642',1));
insert into associated_SigleToProgram(values ('GIF643',1));
insert into associated_SigleToProgram(values ('GIF644',1));
insert into associated_SigleToProgram(values ('GIF650',1));
insert into associated_SigleToProgram(values ('GIF655',1));
insert into associated_SigleToProgram(values ('GIF660',1));
insert into associated_SigleToProgram(values ('GIF670',1));
insert into associated_SigleToProgram(values ('GIF671',1));
insert into associated_SigleToProgram(values ('GIF672',1));
insert into associated_SigleToProgram(values ('GIF673',1));
insert into associated_SigleToProgram(values ('GIF675',1));
insert into associated_SigleToProgram(values ('GIF680',1));
insert into associated_SigleToProgram(values ('GIF685',1));
insert into associated_SigleToProgram(values ('GIF690',1));
insert into associated_SigleToProgram(values ('GIF691',1));
insert into associated_SigleToProgram(values ('GIF692',1));
insert into associated_SigleToProgram(values ('GIF701',1));
insert into associated_SigleToProgram(values ('GIF801',1));
insert into associated_SigleToProgram(values ('GIF825',1));
insert into associated_SigleToProgram(values ('GIF201',2));
insert into associated_SigleToProgram(values ('GIF230',2));
insert into associated_SigleToProgram(values ('GIF242',2));
insert into associated_SigleToProgram(values ('GIF261',2));
insert into associated_SigleToProgram(values ('GIF270',2));
insert into associated_SigleToProgram(values ('GIF301',2));
insert into associated_SigleToProgram(values ('GIF302',2));
insert into associated_SigleToProgram(values ('GIF310',2));
insert into associated_SigleToProgram(values ('GIF320',2));
insert into associated_SigleToProgram(values ('GIF331',2));
insert into associated_SigleToProgram(values ('GIF332',2));
insert into associated_SigleToProgram(values ('GIF333',2));
insert into associated_SigleToProgram(values ('GIF340',2));
insert into associated_SigleToProgram(values ('GIF350',2));
insert into associated_SigleToProgram(values ('GIF360',2));
insert into associated_SigleToProgram(values ('GIF362',2));
insert into associated_SigleToProgram(values ('GIF370',2));
insert into associated_SigleToProgram(values ('GIF371',2));
insert into associated_SigleToProgram(values ('GIF380',2));
insert into associated_SigleToProgram(values ('GIF390',2));
insert into associated_SigleToProgram(values ('GIF391',2));
insert into associated_SigleToProgram(values ('GIF400',2));
insert into associated_SigleToProgram(values ('GIF401',2));
insert into associated_SigleToProgram(values ('GIF402',2));
insert into associated_SigleToProgram(values ('GIF421',2));
insert into associated_SigleToProgram(values ('GIF442',2));
insert into associated_SigleToProgram(values ('GIF443',2));
insert into associated_SigleToProgram(values ('GIF450',2));
insert into associated_SigleToProgram(values ('GIF460',2));
insert into associated_SigleToProgram(values ('GIF470',2));
insert into associated_SigleToProgram(values ('GIF480',2));
insert into associated_SigleToProgram(values ('GIF500',2));
insert into associated_SigleToProgram(values ('GIF501',2));
insert into associated_SigleToProgram(values ('GIF510',2));
insert into associated_SigleToProgram(values ('GIF521',2));
insert into associated_SigleToProgram(values ('GIF530',2));
insert into associated_SigleToProgram(values ('GIF540',2));
insert into associated_SigleToProgram(values ('GIF550',2));
insert into associated_SigleToProgram(values ('GIF560',2));
insert into associated_SigleToProgram(values ('GIF570',2));
insert into associated_SigleToProgram(values ('GIF580',2));
insert into associated_SigleToProgram(values ('GIF590',2));
insert into associated_SigleToProgram(values ('GIF591',2));
insert into associated_SigleToProgram(values ('GIF592',2));
insert into associated_SigleToProgram(values ('GIF600',2));
insert into associated_SigleToProgram(values ('GIF601',2));
insert into associated_SigleToProgram(values ('GIF611',2));
insert into associated_SigleToProgram(values ('GIF620',2));
insert into associated_SigleToProgram(values ('GIF630',2));
insert into associated_SigleToProgram(values ('GIF640',2));
insert into associated_SigleToProgram(values ('GIF642',2));
insert into associated_SigleToProgram(values ('GIF643',2));
insert into associated_SigleToProgram(values ('GIF644',2));
insert into associated_SigleToProgram(values ('GIF650',2));
insert into associated_SigleToProgram(values ('GIF655',2));
insert into associated_SigleToProgram(values ('GIF660',2));
insert into associated_SigleToProgram(values ('GIF670',2));
insert into associated_SigleToProgram(values ('GIF671',2));
insert into associated_SigleToProgram(values ('GIF672',2));
insert into associated_SigleToProgram(values ('GIF673',2));
insert into associated_SigleToProgram(values ('GIF675',2));
insert into associated_SigleToProgram(values ('GIF680',2));
insert into associated_SigleToProgram(values ('GIF685',2));
insert into associated_SigleToProgram(values ('GIF690',2));
insert into associated_SigleToProgram(values ('GIF691',2));
insert into associated_SigleToProgram(values ('GIF692',2));
insert into associated_SigleToProgram(values ('GIF701',2));
insert into associated_SigleToProgram(values ('GIF801',2));
insert into associated_SigleToProgram(values ('GIF825',2));
insert into associated_SigleToProgram(values ('GIN651',1));
insert into associated_SigleToProgram(values ('GIN652',1));
insert into associated_SigleToProgram(values ('GIN653',1));
insert into associated_SigleToProgram(values ('GIN654',1));
insert into associated_SigleToProgram(values ('GIN655',1));
insert into associated_SigleToProgram(values ('GIN656',1));
insert into associated_SigleToProgram(values ('GIN661',1));
insert into associated_SigleToProgram(values ('GIN662',1));
insert into associated_SigleToProgram(values ('GIN663',1));
insert into associated_SigleToProgram(values ('GIN664',1));
insert into associated_SigleToProgram(values ('GIN665',1));
insert into associated_SigleToProgram(values ('GIN666',1));
